"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * DataSpray Umbrella Shield API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ConfigToJSONTyped = exports.ConfigToJSON = exports.ConfigFromJSONTyped = exports.ConfigFromJSON = exports.instanceOfConfig = void 0;
var OperationMode_js_1 = require("./OperationMode.js");
/**
 * Check if a given object implements the Config interface.
 */
function instanceOfConfig(value) {
    if (!('mode' in value) || value['mode'] === undefined)
        return false;
    return true;
}
exports.instanceOfConfig = instanceOfConfig;
function ConfigFromJSON(json) {
    return ConfigFromJSONTyped(json, false);
}
exports.ConfigFromJSON = ConfigFromJSON;
function ConfigFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'mode': (0, OperationMode_js_1.OperationModeFromJSON)(json['mode']),
        'timeoutMs': json['timeoutMs'] == null ? undefined : json['timeoutMs'],
        'collectAdditionalHeaders': json['collectAdditionalHeaders'] == null ? undefined : json['collectAdditionalHeaders'],
    };
}
exports.ConfigFromJSONTyped = ConfigFromJSONTyped;
function ConfigToJSON(json) {
    return ConfigToJSONTyped(json, false);
}
exports.ConfigToJSON = ConfigToJSON;
function ConfigToJSONTyped(value, ignoreDiscriminator) {
    if (ignoreDiscriminator === void 0) { ignoreDiscriminator = false; }
    if (value == null) {
        return value;
    }
    return {
        'mode': (0, OperationMode_js_1.OperationModeToJSON)(value['mode']),
        'timeoutMs': value['timeoutMs'],
        'collectAdditionalHeaders': value['collectAdditionalHeaders'],
    };
}
exports.ConfigToJSONTyped = ConfigToJSONTyped;
