"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * DataSpray Umbrella Shield API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.CookieToJSONTyped = exports.CookieToJSON = exports.CookieFromJSONTyped = exports.CookieFromJSON = exports.instanceOfCookie = void 0;
/**
 * Check if a given object implements the Cookie interface.
 */
function instanceOfCookie(value) {
    if (!('name' in value) || value['name'] === undefined)
        return false;
    if (!('value' in value) || value['value'] === undefined)
        return false;
    return true;
}
exports.instanceOfCookie = instanceOfCookie;
function CookieFromJSON(json) {
    return CookieFromJSONTyped(json, false);
}
exports.CookieFromJSON = CookieFromJSON;
function CookieFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'name': json['name'],
        'value': json['value'],
        'maxAge': json['maxAge'] == null ? undefined : json['maxAge'],
        'domain': json['domain'] == null ? undefined : json['domain'],
        'path': json['path'] == null ? undefined : json['path'],
        'secure': json['secure'] == null ? undefined : json['secure'],
        'httpOnly': json['httpOnly'] == null ? undefined : json['httpOnly'],
        'sameSite': json['sameSite'] == null ? undefined : json['sameSite'],
    };
}
exports.CookieFromJSONTyped = CookieFromJSONTyped;
function CookieToJSON(json) {
    return CookieToJSONTyped(json, false);
}
exports.CookieToJSON = CookieToJSON;
function CookieToJSONTyped(value, ignoreDiscriminator) {
    if (ignoreDiscriminator === void 0) { ignoreDiscriminator = false; }
    if (value == null) {
        return value;
    }
    return {
        'name': value['name'],
        'value': value['value'],
        'maxAge': value['maxAge'],
        'domain': value['domain'],
        'path': value['path'],
        'secure': value['secure'],
        'httpOnly': value['httpOnly'],
        'sameSite': value['sameSite'],
    };
}
exports.CookieToJSONTyped = CookieToJSONTyped;
