"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * DataSpray Umbrella Shield API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.EventRequestToJSONTyped = exports.EventRequestToJSON = exports.EventRequestFromJSONTyped = exports.EventRequestFromJSON = exports.instanceOfEventRequest = void 0;
var OperationMode_js_1 = require("./OperationMode.js");
/**
 * Check if a given object implements the EventRequest interface.
 */
function instanceOfEventRequest(value) {
    if (!('nodeId' in value) || value['nodeId'] === undefined)
        return false;
    if (!('currentMode' in value) || value['currentMode'] === undefined)
        return false;
    if (!('key' in value) || value['key'] === undefined)
        return false;
    if (!('metadata' in value) || value['metadata'] === undefined)
        return false;
    return true;
}
exports.instanceOfEventRequest = instanceOfEventRequest;
function EventRequestFromJSON(json) {
    return EventRequestFromJSONTyped(json, false);
}
exports.EventRequestFromJSON = EventRequestFromJSON;
function EventRequestFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'nodeId': json['nodeId'],
        'currentMode': (0, OperationMode_js_1.OperationModeFromJSON)(json['currentMode']),
        'key': json['key'],
        'metadata': json['metadata'],
    };
}
exports.EventRequestFromJSONTyped = EventRequestFromJSONTyped;
function EventRequestToJSON(json) {
    return EventRequestToJSONTyped(json, false);
}
exports.EventRequestToJSON = EventRequestToJSON;
function EventRequestToJSONTyped(value, ignoreDiscriminator) {
    if (ignoreDiscriminator === void 0) { ignoreDiscriminator = false; }
    if (value == null) {
        return value;
    }
    return {
        'nodeId': value['nodeId'],
        'currentMode': (0, OperationMode_js_1.OperationModeToJSON)(value['currentMode']),
        'key': value['key'],
        'metadata': value['metadata'],
    };
}
exports.EventRequestToJSONTyped = EventRequestToJSONTyped;
