"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * DataSpray Umbrella Shield API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.EventResponseToJSONTyped = exports.EventResponseToJSON = exports.EventResponseFromJSONTyped = exports.EventResponseFromJSON = exports.instanceOfEventResponse = void 0;
var Config_js_1 = require("./Config.js");
/**
 * Check if a given object implements the EventResponse interface.
 */
function instanceOfEventResponse(value) {
    if (!('action' in value) || value['action'] === undefined)
        return false;
    return true;
}
exports.instanceOfEventResponse = instanceOfEventResponse;
function EventResponseFromJSON(json) {
    return EventResponseFromJSONTyped(json, false);
}
exports.EventResponseFromJSON = EventResponseFromJSON;
function EventResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'action': json['action'],
        'configRefresh': json['configRefresh'] == null ? undefined : (0, Config_js_1.ConfigFromJSON)(json['configRefresh']),
    };
}
exports.EventResponseFromJSONTyped = EventResponseFromJSONTyped;
function EventResponseToJSON(json) {
    return EventResponseToJSONTyped(json, false);
}
exports.EventResponseToJSON = EventResponseToJSON;
function EventResponseToJSONTyped(value, ignoreDiscriminator) {
    if (ignoreDiscriminator === void 0) { ignoreDiscriminator = false; }
    if (value == null) {
        return value;
    }
    return {
        'action': value['action'],
        'configRefresh': (0, Config_js_1.ConfigToJSON)(value['configRefresh']),
    };
}
exports.EventResponseToJSONTyped = EventResponseToJSONTyped;
