"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * DataSpray Umbrella Shield API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.HttpMetadataToJSONTyped = exports.HttpMetadataToJSON = exports.HttpMetadataFromJSONTyped = exports.HttpMetadataFromJSON = exports.instanceOfHttpMetadata = void 0;
/**
 * Check if a given object implements the HttpMetadata interface.
 */
function instanceOfHttpMetadata(value) {
    return true;
}
exports.instanceOfHttpMetadata = instanceOfHttpMetadata;
function HttpMetadataFromJSON(json) {
    return HttpMetadataFromJSONTyped(json, false);
}
exports.HttpMetadataFromJSON = HttpMetadataFromJSON;
function HttpMetadataFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'ts': json['ts'] == null ? undefined : (new Date(json['ts'])),
        'uri': json['uri'] == null ? undefined : json['uri'],
        'method': json['method'] == null ? undefined : json['method'],
        'proto': json['proto'] == null ? undefined : json['proto'],
        'ip': json['ip'] == null ? undefined : json['ip'],
        'hXFwdProto': json['hXFwdProto'] == null ? undefined : json['hXFwdProto'],
        'hCfConnIp': json['hCfConnIp'] == null ? undefined : json['hCfConnIp'],
        'hTrueClientIp': json['hTrueClientIp'] == null ? undefined : json['hTrueClientIp'],
        'hXRealIp': json['hXRealIp'] == null ? undefined : json['hXRealIp'],
        'hFwd': json['hFwd'] == null ? undefined : json['hFwd'],
        'hXFwdFor': json['hXFwdFor'] == null ? undefined : json['hXFwdFor'],
        'hVia': json['hVia'] == null ? undefined : json['hVia'],
        'port': json['port'] == null ? undefined : json['port'],
        'hXFwdPort': json['hXFwdPort'] == null ? undefined : json['hXFwdPort'],
        'hXFwdHost': json['hXFwdHost'] == null ? undefined : json['hXFwdHost'],
        'hXReqWith': json['hXReqWith'] == null ? undefined : json['hXReqWith'],
        'hUserAgent': json['hUserAgent'] == null ? undefined : json['hUserAgent'],
        'hAuthPrefix': json['hAuthPrefix'] == null ? undefined : json['hAuthPrefix'],
        'hAuthSize': json['hAuthSize'] == null ? undefined : json['hAuthSize'],
        'hXReqId': json['hXReqId'] == null ? undefined : json['hXReqId'],
        'hAccept': json['hAccept'] == null ? undefined : json['hAccept'],
        'hAcceptLanguage': json['hAcceptLanguage'] == null ? undefined : json['hAcceptLanguage'],
        'hAcceptCharset': json['hAcceptCharset'] == null ? undefined : json['hAcceptCharset'],
        'hAcceptEncoding': json['hAcceptEncoding'] == null ? undefined : json['hAcceptEncoding'],
        'hConnection': json['hConnection'] == null ? undefined : json['hConnection'],
        'hContentType': json['hContentType'] == null ? undefined : json['hContentType'],
        'hFrom': json['hFrom'] == null ? undefined : json['hFrom'],
        'hHost': json['hHost'] == null ? undefined : json['hHost'],
        'hOrigin': json['hOrigin'] == null ? undefined : json['hOrigin'],
        'contentLength': json['contentLength'] == null ? undefined : json['contentLength'],
        'hPragma': json['hPragma'] == null ? undefined : json['hPragma'],
        'hReferer': json['hReferer'] == null ? undefined : json['hReferer'],
        'hSecChDevMem': json['hSecChDevMem'] == null ? undefined : json['hSecChDevMem'],
        'hSecChUa': json['hSecChUa'] == null ? undefined : json['hSecChUa'],
        'hSecChUaModel': json['hSecChUaModel'] == null ? undefined : json['hSecChUaModel'],
        'hSecChUaFull': json['hSecChUaFull'] == null ? undefined : json['hSecChUaFull'],
        'hSecChUaMobile': json['hSecChUaMobile'] == null ? undefined : json['hSecChUaMobile'],
        'hSecChUaPlatform': json['hSecChUaPlatform'] == null ? undefined : json['hSecChUaPlatform'],
        'hSecChUaArch': json['hSecChUaArch'] == null ? undefined : json['hSecChUaArch'],
        'hSecFetchDest': json['hSecFetchDest'] == null ? undefined : json['hSecFetchDest'],
        'hSecFetchMode': json['hSecFetchMode'] == null ? undefined : json['hSecFetchMode'],
        'hSecFetchSite': json['hSecFetchSite'] == null ? undefined : json['hSecFetchSite'],
        'hSecFetchUser': json['hSecFetchUser'] == null ? undefined : json['hSecFetchUser'],
        'tlsCipher': json['tlsCipher'] == null ? undefined : json['tlsCipher'],
        'tlsProto': json['tlsProto'] == null ? undefined : json['tlsProto'],
        'headerNames': json['headerNames'] == null ? undefined : json['headerNames'],
        'cookieNames': json['cookieNames'] == null ? undefined : json['cookieNames'],
        'additionalHeaders': json['additionalHeaders'] == null ? undefined : json['additionalHeaders'],
    };
}
exports.HttpMetadataFromJSONTyped = HttpMetadataFromJSONTyped;
function HttpMetadataToJSON(json) {
    return HttpMetadataToJSONTyped(json, false);
}
exports.HttpMetadataToJSON = HttpMetadataToJSON;
function HttpMetadataToJSONTyped(value, ignoreDiscriminator) {
    if (ignoreDiscriminator === void 0) { ignoreDiscriminator = false; }
    if (value == null) {
        return value;
    }
    return {
        'ts': value['ts'] == null ? undefined : ((value['ts']).toISOString()),
        'uri': value['uri'],
        'method': value['method'],
        'proto': value['proto'],
        'ip': value['ip'],
        'hXFwdProto': value['hXFwdProto'],
        'hCfConnIp': value['hCfConnIp'],
        'hTrueClientIp': value['hTrueClientIp'],
        'hXRealIp': value['hXRealIp'],
        'hFwd': value['hFwd'],
        'hXFwdFor': value['hXFwdFor'],
        'hVia': value['hVia'],
        'port': value['port'],
        'hXFwdPort': value['hXFwdPort'],
        'hXFwdHost': value['hXFwdHost'],
        'hXReqWith': value['hXReqWith'],
        'hUserAgent': value['hUserAgent'],
        'hAuthPrefix': value['hAuthPrefix'],
        'hAuthSize': value['hAuthSize'],
        'hXReqId': value['hXReqId'],
        'hAccept': value['hAccept'],
        'hAcceptLanguage': value['hAcceptLanguage'],
        'hAcceptCharset': value['hAcceptCharset'],
        'hAcceptEncoding': value['hAcceptEncoding'],
        'hConnection': value['hConnection'],
        'hContentType': value['hContentType'],
        'hFrom': value['hFrom'],
        'hHost': value['hHost'],
        'hOrigin': value['hOrigin'],
        'contentLength': value['contentLength'],
        'hPragma': value['hPragma'],
        'hReferer': value['hReferer'],
        'hSecChDevMem': value['hSecChDevMem'],
        'hSecChUa': value['hSecChUa'],
        'hSecChUaModel': value['hSecChUaModel'],
        'hSecChUaFull': value['hSecChUaFull'],
        'hSecChUaMobile': value['hSecChUaMobile'],
        'hSecChUaPlatform': value['hSecChUaPlatform'],
        'hSecChUaArch': value['hSecChUaArch'],
        'hSecFetchDest': value['hSecFetchDest'],
        'hSecFetchMode': value['hSecFetchMode'],
        'hSecFetchSite': value['hSecFetchSite'],
        'hSecFetchUser': value['hSecFetchUser'],
        'tlsCipher': value['tlsCipher'],
        'tlsProto': value['tlsProto'],
        'headerNames': value['headerNames'],
        'cookieNames': value['cookieNames'],
        'additionalHeaders': value['additionalHeaders'],
    };
}
exports.HttpMetadataToJSONTyped = HttpMetadataToJSONTyped;
