"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * DataSpray Umbrella Shield API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.HttpActionToJSONTyped = exports.HttpActionToJSON = exports.HttpActionFromJSONTyped = exports.HttpActionFromJSON = exports.instanceOfHttpAction = void 0;
var Cookie_js_1 = require("./Cookie.js");
var RequestProcess_js_1 = require("./RequestProcess.js");
/**
 * Check if a given object implements the HttpAction interface.
 */
function instanceOfHttpAction(value) {
    if (!('requestProcess' in value) || value['requestProcess'] === undefined)
        return false;
    return true;
}
exports.instanceOfHttpAction = instanceOfHttpAction;
function HttpActionFromJSON(json) {
    return HttpActionFromJSONTyped(json, false);
}
exports.HttpActionFromJSON = HttpActionFromJSON;
function HttpActionFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'requestProcess': (0, RequestProcess_js_1.RequestProcessFromJSON)(json['requestProcess']),
        'responseStatus': json['responseStatus'] == null ? undefined : json['responseStatus'],
        'requestMetadata': json['requestMetadata'] == null ? undefined : json['requestMetadata'],
        'responseHeaders': json['responseHeaders'] == null ? undefined : json['responseHeaders'],
        'responseCookies': json['responseCookies'] == null ? undefined : (json['responseCookies'].map(Cookie_js_1.CookieFromJSON)),
    };
}
exports.HttpActionFromJSONTyped = HttpActionFromJSONTyped;
function HttpActionToJSON(json) {
    return HttpActionToJSONTyped(json, false);
}
exports.HttpActionToJSON = HttpActionToJSON;
function HttpActionToJSONTyped(value, ignoreDiscriminator) {
    if (ignoreDiscriminator === void 0) { ignoreDiscriminator = false; }
    if (value == null) {
        return value;
    }
    return {
        'requestProcess': (0, RequestProcess_js_1.RequestProcessToJSON)(value['requestProcess']),
        'responseStatus': value['responseStatus'],
        'requestMetadata': value['requestMetadata'],
        'responseHeaders': value['responseHeaders'],
        'responseCookies': value['responseCookies'] == null ? undefined : (value['responseCookies'].map(Cookie_js_1.CookieToJSON)),
    };
}
exports.HttpActionToJSONTyped = HttpActionToJSONTyped;
