"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * DataSpray Umbrella Shield API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.HttpEventRequestToJSONTyped = exports.HttpEventRequestToJSON = exports.HttpEventRequestFromJSONTyped = exports.HttpEventRequestFromJSON = exports.instanceOfHttpEventRequest = void 0;
var HttpMetadata_js_1 = require("./HttpMetadata.js");
var OperationMode_js_1 = require("./OperationMode.js");
/**
 * Check if a given object implements the HttpEventRequest interface.
 */
function instanceOfHttpEventRequest(value) {
    if (!('nodeId' in value) || value['nodeId'] === undefined)
        return false;
    if (!('currentMode' in value) || value['currentMode'] === undefined)
        return false;
    if (!('httpMetadata' in value) || value['httpMetadata'] === undefined)
        return false;
    return true;
}
exports.instanceOfHttpEventRequest = instanceOfHttpEventRequest;
function HttpEventRequestFromJSON(json) {
    return HttpEventRequestFromJSONTyped(json, false);
}
exports.HttpEventRequestFromJSON = HttpEventRequestFromJSON;
function HttpEventRequestFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'nodeId': json['nodeId'],
        'currentMode': (0, OperationMode_js_1.OperationModeFromJSON)(json['currentMode']),
        'httpMetadata': (0, HttpMetadata_js_1.HttpMetadataFromJSON)(json['httpMetadata']),
    };
}
exports.HttpEventRequestFromJSONTyped = HttpEventRequestFromJSONTyped;
function HttpEventRequestToJSON(json) {
    return HttpEventRequestToJSONTyped(json, false);
}
exports.HttpEventRequestToJSON = HttpEventRequestToJSON;
function HttpEventRequestToJSONTyped(value, ignoreDiscriminator) {
    if (ignoreDiscriminator === void 0) { ignoreDiscriminator = false; }
    if (value == null) {
        return value;
    }
    return {
        'nodeId': value['nodeId'],
        'currentMode': (0, OperationMode_js_1.OperationModeToJSON)(value['currentMode']),
        'httpMetadata': (0, HttpMetadata_js_1.HttpMetadataToJSON)(value['httpMetadata']),
    };
}
exports.HttpEventRequestToJSONTyped = HttpEventRequestToJSONTyped;
