"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * DataSpray Umbrella Shield API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.HttpEventResponseToJSONTyped = exports.HttpEventResponseToJSON = exports.HttpEventResponseFromJSONTyped = exports.HttpEventResponseFromJSON = exports.instanceOfHttpEventResponse = void 0;
var Config_js_1 = require("./Config.js");
var HttpAction_js_1 = require("./HttpAction.js");
/**
 * Check if a given object implements the HttpEventResponse interface.
 */
function instanceOfHttpEventResponse(value) {
    if (!('action' in value) || value['action'] === undefined)
        return false;
    return true;
}
exports.instanceOfHttpEventResponse = instanceOfHttpEventResponse;
function HttpEventResponseFromJSON(json) {
    return HttpEventResponseFromJSONTyped(json, false);
}
exports.HttpEventResponseFromJSON = HttpEventResponseFromJSON;
function HttpEventResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'action': (0, HttpAction_js_1.HttpActionFromJSON)(json['action']),
        'configRefresh': json['configRefresh'] == null ? undefined : (0, Config_js_1.ConfigFromJSON)(json['configRefresh']),
    };
}
exports.HttpEventResponseFromJSONTyped = HttpEventResponseFromJSONTyped;
function HttpEventResponseToJSON(json) {
    return HttpEventResponseToJSONTyped(json, false);
}
exports.HttpEventResponseToJSON = HttpEventResponseToJSON;
function HttpEventResponseToJSONTyped(value, ignoreDiscriminator) {
    if (ignoreDiscriminator === void 0) { ignoreDiscriminator = false; }
    if (value == null) {
        return value;
    }
    return {
        'action': (0, HttpAction_js_1.HttpActionToJSON)(value['action']),
        'configRefresh': (0, Config_js_1.ConfigToJSON)(value['configRefresh']),
    };
}
exports.HttpEventResponseToJSONTyped = HttpEventResponseToJSONTyped;
