"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * DataSpray Umbrella Shield API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.OperationModeToJSONTyped = exports.OperationModeToJSON = exports.OperationModeFromJSONTyped = exports.OperationModeFromJSON = exports.instanceOfOperationMode = exports.OperationMode = void 0;
/**
 *
 * @export
 */
exports.OperationMode = {
    Blocking: 'BLOCKING',
    Monitor: 'MONITOR',
    Disabled: 'DISABLED'
};
function instanceOfOperationMode(value) {
    for (var key in exports.OperationMode) {
        if (Object.prototype.hasOwnProperty.call(exports.OperationMode, key)) {
            if (exports.OperationMode[key] === value) {
                return true;
            }
        }
    }
    return false;
}
exports.instanceOfOperationMode = instanceOfOperationMode;
function OperationModeFromJSON(json) {
    return OperationModeFromJSONTyped(json, false);
}
exports.OperationModeFromJSON = OperationModeFromJSON;
function OperationModeFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
exports.OperationModeFromJSONTyped = OperationModeFromJSONTyped;
function OperationModeToJSON(value) {
    return value;
}
exports.OperationModeToJSON = OperationModeToJSON;
function OperationModeToJSONTyped(value, ignoreDiscriminator) {
    return value;
}
exports.OperationModeToJSONTyped = OperationModeToJSONTyped;
