"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * DataSpray Umbrella Shield API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.PingRequestToJSONTyped = exports.PingRequestToJSON = exports.PingRequestFromJSONTyped = exports.PingRequestFromJSON = exports.instanceOfPingRequest = void 0;
/**
 * Check if a given object implements the PingRequest interface.
 */
function instanceOfPingRequest(value) {
    if (!('nodeId' in value) || value['nodeId'] === undefined)
        return false;
    return true;
}
exports.instanceOfPingRequest = instanceOfPingRequest;
function PingRequestFromJSON(json) {
    return PingRequestFromJSONTyped(json, false);
}
exports.PingRequestFromJSON = PingRequestFromJSON;
function PingRequestFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'nodeId': json['nodeId'],
    };
}
exports.PingRequestFromJSONTyped = PingRequestFromJSONTyped;
function PingRequestToJSON(json) {
    return PingRequestToJSONTyped(json, false);
}
exports.PingRequestToJSON = PingRequestToJSON;
function PingRequestToJSONTyped(value, ignoreDiscriminator) {
    if (ignoreDiscriminator === void 0) { ignoreDiscriminator = false; }
    if (value == null) {
        return value;
    }
    return {
        'nodeId': value['nodeId'],
    };
}
exports.PingRequestToJSONTyped = PingRequestToJSONTyped;
