"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * DataSpray Umbrella Shield API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.PingResponseToJSONTyped = exports.PingResponseToJSON = exports.PingResponseFromJSONTyped = exports.PingResponseFromJSON = exports.instanceOfPingResponse = void 0;
var Config_js_1 = require("./Config.js");
/**
 * Check if a given object implements the PingResponse interface.
 */
function instanceOfPingResponse(value) {
    if (!('config' in value) || value['config'] === undefined)
        return false;
    return true;
}
exports.instanceOfPingResponse = instanceOfPingResponse;
function PingResponseFromJSON(json) {
    return PingResponseFromJSONTyped(json, false);
}
exports.PingResponseFromJSON = PingResponseFromJSON;
function PingResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'config': (0, Config_js_1.ConfigFromJSON)(json['config']),
    };
}
exports.PingResponseFromJSONTyped = PingResponseFromJSONTyped;
function PingResponseToJSON(json) {
    return PingResponseToJSONTyped(json, false);
}
exports.PingResponseToJSON = PingResponseToJSON;
function PingResponseToJSONTyped(value, ignoreDiscriminator) {
    if (ignoreDiscriminator === void 0) { ignoreDiscriminator = false; }
    if (value == null) {
        return value;
    }
    return {
        'config': (0, Config_js_1.ConfigToJSON)(value['config']),
    };
}
exports.PingResponseToJSONTyped = PingResponseToJSONTyped;
