"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * DataSpray Umbrella Shield API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.RequestProcessToJSONTyped = exports.RequestProcessToJSON = exports.RequestProcessFromJSONTyped = exports.RequestProcessFromJSON = exports.instanceOfRequestProcess = exports.RequestProcess = void 0;
/**
 *
 * @export
 */
exports.RequestProcess = {
    Allow: 'ALLOW',
    Block: 'BLOCK'
};
function instanceOfRequestProcess(value) {
    for (var key in exports.RequestProcess) {
        if (Object.prototype.hasOwnProperty.call(exports.RequestProcess, key)) {
            if (exports.RequestProcess[key] === value) {
                return true;
            }
        }
    }
    return false;
}
exports.instanceOfRequestProcess = instanceOfRequestProcess;
function RequestProcessFromJSON(json) {
    return RequestProcessFromJSONTyped(json, false);
}
exports.RequestProcessFromJSON = RequestProcessFromJSON;
function RequestProcessFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
exports.RequestProcessFromJSONTyped = RequestProcessFromJSONTyped;
function RequestProcessToJSON(value) {
    return value;
}
exports.RequestProcessToJSON = RequestProcessToJSON;
function RequestProcessToJSONTyped(value, ignoreDiscriminator) {
    return value;
}
exports.RequestProcessToJSONTyped = RequestProcessToJSONTyped;
