name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[release]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: 'maven'
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Setup asdf
        uses: asdf-vm/actions/setup@v3
      - name: Setup dst
        run: |
          asdf plugin add dst https://github.com/datasprayio/asdf-dst.git
          asdf install

      - name: Maven build
        timeout-minutes: 30
        run: mvn clean install --no-transfer-progress
