name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[release]') && (github.event_name != 'push')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: sdkman/sdkman-action@b1f9b696c79148b66d3d3a06f7ea801820318d0f
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Setup asdf
        uses: asdf-vm/actions/setup@v3
      - name: Setup dst
        run: |
          asdf plugin add dst https://github.com/datasprayio/asdf-dst.git
          asdf install
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Maven build
        timeout-minutes: 30
        run: mvn clean install --no-transfer-progress
